app:
    resource: "@AppBundle/Controller/"
    prefix:   /
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

rest_routes:
    resource: "@AppBundle/Resources/config/rest_routing.yml"
    type: rest
    prefix: /api